/* The following code was generated by JFlex 1.4.1 on 2/22/09 4:48 PM */

/*
 * Copyright 2000-2009 Red Shark Technology
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jetbrains.plugins.clojure.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import java.util.*;
import java.io.CharArrayReader;
import org.jetbrains.annotations.NotNull;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 2/22/09 4:48 PM from the specification file
 * <tt>src/org/jetbrains/plugins/clojure/lexer/clojure.flex</tt>
 */
public class _ClojureLexer implements ClojureTokenTypes, FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int SYMBOL = 1;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\1\1\0\1\2\1\1\22\0\1\2\1\42\1\34"+
    "\1\16\1\33\1\20\1\21\1\14\1\6\1\7\1\42\1\42\1\3"+
    "\1\42\1\5\1\43\1\36\2\4\1\36\1\36\2\4\1\36\2\4"+
    "\1\44\1\40\1\42\1\42\1\42\1\42\1\23\6\24\24\41\1\10"+
    "\1\25\1\11\1\17\1\41\1\15\1\50\1\31\2\24\1\47\1\32"+
    "\2\41\1\45\2\41\1\46\1\41\1\26\3\41\1\27\1\51\1\30"+
    "\1\35\5\41\1\12\1\0\1\13\1\22\43\0\4\37\4\0\1\37"+
    "\12\0\1\37\4\0\1\37\5\0\27\37\1\0\37\37\1\0\u013f\37"+
    "\31\0\162\37\4\0\14\37\16\0\5\37\11\0\1\37\213\0\1\37"+
    "\13\0\1\37\1\0\3\37\1\0\1\37\1\0\24\37\1\0\54\37"+
    "\1\0\46\37\1\0\5\37\4\0\202\37\10\0\105\37\1\0\46\37"+
    "\2\0\2\37\6\0\20\37\41\0\46\37\2\0\1\37\7\0\47\37"+
    "\110\0\33\37\5\0\3\37\56\0\32\37\5\0\13\37\43\0\2\37"+
    "\1\0\143\37\1\0\1\37\17\0\2\37\7\0\2\37\12\0\3\37"+
    "\2\0\1\37\20\0\1\37\1\0\36\37\35\0\3\37\60\0\46\37"+
    "\13\0\1\37\u0152\0\66\37\3\0\1\37\22\0\1\37\7\0\12\37"+
    "\43\0\10\37\2\0\2\37\2\0\26\37\1\0\7\37\1\0\1\37"+
    "\3\0\4\37\3\0\1\37\36\0\2\37\1\0\3\37\16\0\4\37"+
    "\21\0\6\37\4\0\2\37\2\0\26\37\1\0\7\37\1\0\2\37"+
    "\1\0\2\37\1\0\2\37\37\0\4\37\1\0\1\37\23\0\3\37"+
    "\20\0\11\37\1\0\3\37\1\0\26\37\1\0\7\37\1\0\2\37"+
    "\1\0\5\37\3\0\1\37\22\0\1\37\17\0\2\37\17\0\1\37"+
    "\23\0\10\37\2\0\2\37\2\0\26\37\1\0\7\37\1\0\2\37"+
    "\1\0\5\37\3\0\1\37\36\0\2\37\1\0\3\37\17\0\1\37"+
    "\21\0\1\37\1\0\6\37\3\0\3\37\1\0\4\37\3\0\2\37"+
    "\1\0\1\37\1\0\2\37\3\0\2\37\3\0\3\37\3\0\10\37"+
    "\1\0\3\37\77\0\1\37\13\0\10\37\1\0\3\37\1\0\27\37"+
    "\1\0\12\37\1\0\5\37\46\0\2\37\43\0\10\37\1\0\3\37"+
    "\1\0\27\37\1\0\12\37\1\0\5\37\3\0\1\37\40\0\1\37"+
    "\1\0\2\37\43\0\10\37\1\0\3\37\1\0\27\37\1\0\20\37"+
    "\46\0\2\37\43\0\22\37\3\0\30\37\1\0\11\37\1\0\1\37"+
    "\2\0\7\37\72\0\60\37\1\0\2\37\13\0\10\37\72\0\2\37"+
    "\1\0\1\37\2\0\2\37\1\0\1\37\2\0\1\37\6\0\4\37"+
    "\1\0\7\37\1\0\3\37\1\0\1\37\1\0\1\37\2\0\2\37"+
    "\1\0\4\37\1\0\2\37\11\0\1\37\2\0\5\37\1\0\1\37"+
    "\25\0\2\37\42\0\1\37\77\0\10\37\1\0\42\37\35\0\4\37"+
    "\164\0\42\37\1\0\5\37\1\0\2\37\45\0\6\37\112\0\46\37"+
    "\12\0\51\37\7\0\132\37\5\0\104\37\5\0\122\37\6\0\7\37"+
    "\1\0\77\37\1\0\1\37\1\0\4\37\2\0\7\37\1\0\1\37"+
    "\1\0\4\37\2\0\47\37\1\0\1\37\1\0\4\37\2\0\37\37"+
    "\1\0\1\37\1\0\4\37\2\0\7\37\1\0\1\37\1\0\4\37"+
    "\2\0\7\37\1\0\7\37\1\0\27\37\1\0\37\37\1\0\1\37"+
    "\1\0\4\37\2\0\7\37\1\0\47\37\1\0\23\37\105\0\125\37"+
    "\14\0\u026c\37\2\0\10\37\12\0\32\37\5\0\113\37\3\0\3\37"+
    "\17\0\15\37\1\0\4\37\16\0\22\37\16\0\22\37\16\0\15\37"+
    "\1\0\3\37\17\0\64\37\43\0\1\37\3\0\2\37\103\0\130\37"+
    "\10\0\51\37\127\0\35\37\63\0\36\37\2\0\5\37\u038b\0\154\37"+
    "\224\0\234\37\4\0\132\37\6\0\26\37\2\0\6\37\2\0\46\37"+
    "\2\0\6\37\2\0\10\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\37\37\2\0\65\37\1\0\7\37\1\0\1\37\3\0\3\37"+
    "\1\0\7\37\3\0\4\37\2\0\6\37\4\0\15\37\5\0\3\37"+
    "\1\0\7\37\102\0\2\37\23\0\1\37\34\0\1\37\15\0\1\37"+
    "\40\0\22\37\120\0\1\37\4\0\1\37\2\0\12\37\1\0\1\37"+
    "\3\0\5\37\6\0\1\37\1\0\1\37\1\0\1\37\1\0\4\37"+
    "\1\0\3\37\1\0\7\37\3\0\3\37\5\0\5\37\26\0\44\37"+
    "\u0e81\0\3\37\31\0\11\37\7\0\5\37\2\0\5\37\4\0\126\37"+
    "\6\0\3\37\1\0\137\37\5\0\50\37\4\0\136\37\21\0\30\37"+
    "\70\0\20\37\u0200\0\u19b6\37\112\0\u51a6\37\132\0\u048d\37\u0773\0\u2ba4\37"+
    "\u215c\0\u012e\37\2\0\73\37\225\0\7\37\14\0\5\37\5\0\1\37"+
    "\1\0\12\37\1\0\15\37\1\0\5\37\1\0\1\37\1\0\2\37"+
    "\1\0\2\37\1\0\154\37\41\0\u016b\37\22\0\100\37\2\0\66\37"+
    "\50\0\15\37\66\0\2\37\30\0\3\37\31\0\1\37\6\0\5\37"+
    "\1\0\207\37\7\0\1\37\34\0\32\37\4\0\1\37\1\0\32\37"+
    "\12\0\132\37\3\0\6\37\2\0\6\37\2\0\6\37\2\0\3\37"+
    "\3\0\2\37\3\0\2\37\31\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\5\1\21\1\22\1\1\3\5\1\23\1\24"+
    "\1\25\1\1\1\26\1\25\1\27\1\30\1\31\1\0"+
    "\1\25\1\5\1\32\2\20\1\33\2\34\3\5\1\0"+
    "\1\35\1\36\1\37\2\25\1\40\2\5\1\0\1\36"+
    "\1\41\1\5\1\0\1\42\2\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\124\0\250\0\322\0\124"+
    "\0\124\0\124\0\124\0\124\0\124\0\124\0\124\0\374"+
    "\0\124\0\u0126\0\u0150\0\u017a\0\124\0\u01a4\0\u01ce\0\u01f8"+
    "\0\u0222\0\u024c\0\u0276\0\u0150\0\u02a0\0\124\0\u02ca\0\124"+
    "\0\124\0\124\0\u02f4\0\u031e\0\u0348\0\124\0\u0372\0\124"+
    "\0\124\0\124\0\u039c\0\u03c6\0\u03f0\0\u041a\0\u0444\0\124"+
    "\0\u046e\0\u02f4\0\u0348\0\124\0\u0150\0\u0498\0\u04c2\0\u04ec"+
    "\0\124\0\u0150\0\u0516\0\u0540\0\u0150\0\u056a\0\u0594";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\23\1\26\1\27\1\23\1\30"+
    "\1\23\1\31\1\23\1\32\1\23\1\6\1\3\1\33"+
    "\2\23\1\34\1\35\5\23\4\36\1\37\1\40\10\36"+
    "\1\41\2\36\1\37\2\36\1\37\1\36\6\37\1\36"+
    "\2\37\2\36\2\37\1\42\6\37\53\0\2\4\53\0"+
    "\1\6\1\43\30\0\1\6\17\0\1\23\1\44\10\0"+
    "\1\45\2\0\1\44\2\0\1\44\1\0\6\44\1\0"+
    "\1\44\1\23\2\0\3\44\1\0\5\44\17\0\1\46"+
    "\36\0\1\47\14\0\1\50\14\0\1\47\17\0\1\23"+
    "\1\34\10\0\1\45\2\0\1\23\2\0\1\23\1\0"+
    "\6\23\1\0\2\23\2\0\3\23\1\0\5\23\23\0"+
    "\1\51\26\0\1\52\1\0\22\52\1\53\1\52\6\53"+
    "\1\52\1\53\1\52\1\53\1\52\1\53\3\52\5\53"+
    "\4\0\1\23\1\34\10\0\1\45\2\0\1\23\2\0"+
    "\1\23\1\0\6\23\1\0\2\23\2\0\3\23\1\0"+
    "\1\54\4\23\4\0\1\23\1\34\10\0\1\45\2\0"+
    "\1\23\2\0\1\23\1\0\1\23\1\55\4\23\1\0"+
    "\2\23\2\0\3\23\1\0\5\23\4\0\1\23\1\34"+
    "\10\0\1\45\2\0\1\23\2\0\1\23\1\0\6\23"+
    "\1\0\2\23\2\0\3\23\1\0\3\23\1\56\1\23"+
    "\25\32\1\57\6\32\1\60\15\32\1\33\1\0\50\33"+
    "\5\0\1\61\13\0\1\61\2\0\1\61\1\0\6\61"+
    "\1\0\1\61\3\0\3\61\1\0\5\61\4\0\1\37"+
    "\11\0\1\41\2\0\1\37\2\0\1\37\1\0\6\37"+
    "\1\0\2\37\2\0\2\37\1\0\6\37\4\0\1\62"+
    "\31\0\1\62\17\0\2\44\10\0\1\63\2\0\1\44"+
    "\2\0\1\44\1\0\6\44\1\0\2\44\2\0\3\44"+
    "\1\0\5\44\5\0\1\64\50\0\1\47\31\0\1\47"+
    "\37\0\1\53\1\0\6\53\1\0\1\53\1\0\1\53"+
    "\1\0\1\53\3\0\5\53\4\0\1\23\1\34\10\0"+
    "\1\45\2\0\1\23\2\0\1\23\1\0\6\23\1\0"+
    "\2\23\2\0\3\23\1\0\1\23\1\65\3\23\4\0"+
    "\1\23\1\34\10\0\1\45\2\0\1\23\2\0\1\23"+
    "\1\0\6\23\1\0\1\66\1\23\2\0\3\23\1\0"+
    "\5\23\4\0\1\23\1\34\10\0\1\45\2\0\1\23"+
    "\2\0\1\23\1\0\6\23\1\0\2\23\2\0\3\23"+
    "\1\0\1\23\1\67\3\23\1\0\1\32\3\0\1\32"+
    "\6\0\1\32\10\0\10\32\1\70\1\32\17\0\2\61"+
    "\10\0\1\71\2\0\1\61\2\0\1\61\1\0\6\61"+
    "\1\0\2\61\2\0\3\61\1\0\5\61\4\0\1\23"+
    "\1\34\10\0\1\45\2\0\1\23\2\0\1\23\1\0"+
    "\6\23\1\0\2\23\2\0\3\23\1\0\2\23\1\72"+
    "\2\23\4\0\1\23\1\34\10\0\1\45\2\0\1\23"+
    "\2\0\1\23\1\0\6\23\1\0\2\23\2\0\3\23"+
    "\1\0\4\23\1\73\4\0\1\74\17\0\1\74\4\0"+
    "\2\74\3\0\1\74\10\0\2\74\5\0\1\23\1\34"+
    "\10\0\1\45\2\0\1\23\2\0\1\23\1\0\6\23"+
    "\1\0\2\23\2\0\3\23\1\0\2\23\1\75\2\23"+
    "\4\0\1\76\17\0\1\76\4\0\2\76\3\0\1\76"+
    "\10\0\2\76\5\0\1\77\17\0\1\77\4\0\2\77"+
    "\3\0\1\77\10\0\2\77\5\0\1\32\17\0\1\32"+
    "\4\0\2\32\3\0\1\32\10\0\2\32\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1470];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\2\1\10\11\1\1\1\11"+
    "\3\1\1\11\10\1\1\11\1\1\3\11\1\0\2\1"+
    "\1\11\1\1\3\11\4\1\1\0\1\11\3\1\1\11"+
    "\3\1\1\0\1\11\2\1\1\0\1\1\2\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  /*
  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState) {
    char [] buf = buffer.toString().substring(start,end).toCharArray();
    yyreset( new CharArrayReader( buf ) );
    yybegin(initialState);
  }
  
  public void reset(CharSequence buffer, int initialState){
    reset(buffer, 0, buffer.length(), initialState);
  }
  */


  public _ClojureLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _ClojureLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1290) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  // For Demetra compatibility
  public void reset(CharSequence buffer, int initialState){
    zzBuffer = buffer;
    zzBufferArray = null;
    zzCurrentPos = zzMarkedPos = zzStartRead = 0;
    zzPushbackPos = 0;
    zzAtEOF = false;
    zzAtBOL = true;
    zzEndRead = buffer.length();
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = zzLexicalState;


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 10: 
          { return LEFT_CURLY;
          }
        case 35: break;
        case 3: 
          { return COMMA;
          }
        case 36: break;
        case 12: 
          { return QUOTE;
          }
        case 37: break;
        case 4: 
          { return INTEGER_LITERAL;
          }
        case 38: break;
        case 20: 
          { return LINE_COMMENT;
          }
        case 39: break;
        case 28: 
          { return CHAR_LITERAL;
          }
        case 40: break;
        case 24: 
          { yybegin(YYINITIAL); return symATOM;
          }
        case 41: break;
        case 1: 
          { return BAD_CHARACTER;
          }
        case 42: break;
        case 6: 
          { return LEFT_PAREN;
          }
        case 43: break;
        case 15: 
          { return UP;
          }
        case 44: break;
        case 26: 
          { return SHARPUP;
          }
        case 45: break;
        case 13: 
          { return BACKQUOTE;
          }
        case 46: break;
        case 23: 
          { return symDOT;
          }
        case 47: break;
        case 34: 
          { return FALSE;
          }
        case 48: break;
        case 32: 
          { return NIL;
          }
        case 49: break;
        case 8: 
          { return LEFT_SQUARE;
          }
        case 50: break;
        case 7: 
          { return RIGHT_PAREN;
          }
        case 51: break;
        case 17: 
          { return TILDA;
          }
        case 52: break;
        case 19: 
          { return WRONG_STRING_LITERAL;
          }
        case 53: break;
        case 29: 
          { return STRING_LITERAL;
          }
        case 54: break;
        case 21: 
          { return symATOM;
          }
        case 55: break;
        case 25: 
          { return symNS_SEP;
          }
        case 56: break;
        case 18: 
          { return AT;
          }
        case 57: break;
        case 27: 
          { return TILDAAT;
          }
        case 58: break;
        case 16: 
          { return symIMPLICIT_ARG;
          }
        case 59: break;
        case 31: 
          { return FLOAT_LITERAL;
          }
        case 60: break;
        case 11: 
          { return RIGHT_CURLY;
          }
        case 61: break;
        case 30: 
          { return COLON_SYMBOL;
          }
        case 62: break;
        case 22: 
          { yypushback(yytext().length()); yybegin(YYINITIAL);
          }
        case 63: break;
        case 5: 
          { yypushback(yytext().length()); yybegin(SYMBOL);
          }
        case 64: break;
        case 14: 
          { return SHARP;
          }
        case 65: break;
        case 33: 
          { return TRUE;
          }
        case 66: break;
        case 2: 
          { return WHITESPACE;
          }
        case 67: break;
        case 9: 
          { return RIGHT_SQUARE;
          }
        case 68: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
